{{- if ne .Values.db.type "derby" }}
{{- if not (or .Values.db.secret .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fhir.fullname" . }}-db-secret
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.db.adminPassword }}
  postgres-password: {{ .Values.db.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.db.password }}
  password: {{ .Values.db.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
