apiVersion: v2
description: Helm chart for the LinuxForHealth FHIR Server
name: fhir-server
version: 0.9.0
appVersion: 5.1.1
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: keycloak
    version: 18.4.0
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
sources:
  - https://github.com/LinuxForHealth/lfh-helm
  - https://github.com/LinuxForHealth/FHIR
home: https://linuxforhealth.github.io/FHIR/
type: application
maintainers:
  - name: Lee Surprenant
    email: lmsurpre@merative.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: changed
      description: bumped to LinuxForHealth version 5.1.1
    - kind: changed
      description: bumped to codecentric keycloak chart version 18.4.0
    - kind: changed
      description: bumped to bitnami postgresql chart version 11.9.13
    - kind: changed
      description: split db user creds in two; now uses separate admin user for schematool
    - kind: removed
      description: support for Db2 and all Db2-related values
    - kind: removed
      description: support for networking.k8s.io/v1/beta (kubernetes <1.19)
